import math

# print(math.sqrt(25))
# print(math.pow(5,2))
# print(math.pi)
# print(math.floor(3.5))
# print(math.floor(3.8))
# print(math.floor(3.2))
# print(math.ceil(3.5))
# print(math.ceil(3.8))
# print(math.ceil(3.2))
# print(math.trunc(3.5))
# print(math.trunc(3.8))
# print(math.trunc(3.2))
# print(round(3.5))
# print(round(3.8))
# print(round(3.2))
print(math.cos())
print(math.sin())
print(math.tan())